CREATE TABLE sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(140) NOT NULL,
    description TEXT,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_sections_type CHECK (type IN ('TALLER', 'PARCIAL')),
    CONSTRAINT chk_sections_slug_format CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT chk_sections_display_order_positive CHECK (display_order > 0),
    CONSTRAINT uq_sections_slug UNIQUE (slug),
    CONSTRAINT uq_sections_display_order UNIQUE (display_order),
    CONSTRAINT uq_sections_type_name UNIQUE (type, name)
);

INSERT INTO sections (type, name, slug, description, display_order)
VALUES
    ('TALLER', 'Taller 1', 'taller-1', 'Morfometría de cuencas', 1),
    ('TALLER', 'Taller 2', 'taller-2', 'Estadística y balance hídrico', 2),
    ('TALLER', 'Taller 3', 'taller-3', 'Curva de duración de caudales', 3),
    ('PARCIAL', 'Parcial 1', 'parcial-1', NULL, 4),
    ('PARCIAL', 'Parcial 2', 'parcial-2', NULL, 5),
    ('PARCIAL', 'Parcial 3', 'parcial-3', NULL, 6);
