CREATE TABLE interesting_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    url VARCHAR(2048) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_interesting_links_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_interesting_links_url_not_blank CHECK (btrim(url) <> ''),
    CONSTRAINT chk_interesting_links_url_format CHECK (url ~* '^https?://'),
    CONSTRAINT chk_interesting_links_display_order_non_negative CHECK (display_order >= 0)
);

CREATE INDEX idx_interesting_links_active_order
    ON interesting_links (active, display_order, id);
