CREATE TABLE student_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    nickname VARCHAR(80),
    question TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_questions_section FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE RESTRICT,
    CONSTRAINT chk_student_questions_nickname_not_blank CHECK (nickname IS NULL OR btrim(nickname) <> ''),
    CONSTRAINT chk_student_questions_question_not_blank CHECK (btrim(question) <> ''),
    CONSTRAINT chk_student_questions_question_length CHECK (char_length(question) <= 2000),
    CONSTRAINT chk_student_questions_status CHECK (status IN ('PENDING', 'PUBLISHED', 'ARCHIVED', 'REJECTED'))
);

CREATE INDEX idx_student_questions_section_status_created
    ON student_questions (section_id, status, created_at DESC, id DESC);
