CREATE TABLE question_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL UNIQUE,
    public_id VARCHAR(255) NOT NULL UNIQUE,
    secure_url TEXT NOT NULL,
    format VARCHAR(20) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_question_attachments_question FOREIGN KEY (question_id) REFERENCES student_questions (id) ON DELETE CASCADE,
    CONSTRAINT chk_question_attachments_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT chk_question_attachments_secure_url_not_blank CHECK (btrim(secure_url) <> ''),
    CONSTRAINT chk_question_attachments_format_not_blank CHECK (btrim(format) <> ''),
    CONSTRAINT chk_question_attachments_width_positive CHECK (width > 0),
    CONSTRAINT chk_question_attachments_height_positive CHECK (height > 0),
    CONSTRAINT chk_question_attachments_bytes_positive CHECK (bytes > 0)
);
