CREATE TABLE post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    public_id VARCHAR(255) NOT NULL UNIQUE,
    secure_url TEXT NOT NULL,
    format VARCHAR(20) NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    bytes BIGINT NOT NULL,
    alt_text VARCHAR(180) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_images_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE RESTRICT,
    CONSTRAINT chk_post_images_public_id_not_blank CHECK (btrim(public_id) <> ''),
    CONSTRAINT chk_post_images_secure_url_not_blank CHECK (btrim(secure_url) <> ''),
    CONSTRAINT chk_post_images_format CHECK (format IN ('jpg', 'png')),
    CONSTRAINT chk_post_images_width_positive CHECK (width > 0),
    CONSTRAINT chk_post_images_height_positive CHECK (height > 0),
    CONSTRAINT chk_post_images_bytes_positive CHECK (bytes > 0),
    CONSTRAINT chk_post_images_alt_text_not_blank CHECK (btrim(alt_text) <> '')
);

CREATE INDEX idx_post_images_post
    ON post_images (post_id, id);
