CREATE TABLE site_visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    visited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_site_visits_session UNIQUE (session_id)
);

CREATE INDEX idx_site_visits_visited_at
    ON site_visits (visited_at);

CREATE TABLE section_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    section_id BIGINT NOT NULL,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_section_views_section FOREIGN KEY (section_id) REFERENCES sections (id) ON DELETE RESTRICT,
    CONSTRAINT uq_section_views_session_section UNIQUE (session_id, section_id)
);

CREATE INDEX idx_section_views_viewed_at
    ON section_views (viewed_at);

CREATE INDEX idx_section_views_section
    ON section_views (section_id);

CREATE TABLE post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL,
    post_id BIGINT NOT NULL,
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_post_views_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE RESTRICT,
    CONSTRAINT uq_post_views_session_post UNIQUE (session_id, post_id)
);

CREATE INDEX idx_post_views_viewed_at
    ON post_views (viewed_at);

CREATE INDEX idx_post_views_post
    ON post_views (post_id);
