package edu.udea.hidrologia.question.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.Map;

import javax.sql.DataSource;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.annotation.Transactional;

import edu.udea.hidrologia.question.entity.QuestionAttachment;
import edu.udea.hidrologia.question.entity.StudentQuestion;
import edu.udea.hidrologia.question.entity.StudentQuestionStatus;
import edu.udea.hidrologia.section.entity.Section;
import edu.udea.hidrologia.section.entity.SectionType;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;

@SpringJUnitConfig(StudentQuestionAttachmentPersistenceTest.JpaTestConfig.class)
@Transactional
class StudentQuestionAttachmentPersistenceTest {

    private static final Instant NOW = Instant.parse("2026-01-03T00:00:00Z");

    @Autowired
    private EntityManager entityManager;

    @Autowired
    private StudentQuestionRepository studentQuestionRepository;

    @Autowired
    private QuestionAttachmentRepository questionAttachmentRepository;

    @Test
    void deletingStudentQuestionWithLoadedAttachmentRemovesAttachmentOnFlush() {
        Section section = persistSection();
        StudentQuestion question = studentQuestionRepository.saveAndFlush(new StudentQuestion(
                null,
                section,
                "Camilo",
                "Pregunta con imagen adjunta",
                StudentQuestionStatus.REJECTED,
                NOW,
                NOW));
        QuestionAttachment attachment = questionAttachmentRepository.saveAndFlush(new QuestionAttachment(
                null,
                question,
                "hidrologia-udea/questions/question-1",
                "https://res.cloudinary.com/demo/image/upload/question-1.png",
                "png",
                640,
                480,
                1000L,
                NOW));

        entityManager.clear();

        StudentQuestion reloaded = studentQuestionRepository.findByIdWithSectionAndAttachment(question.getId())
                .orElseThrow();
        assertThat(reloaded.getAttachment()).isNotNull();

        studentQuestionRepository.delete(reloaded);
        studentQuestionRepository.flush();
        entityManager.clear();

        assertThat(studentQuestionRepository.findById(question.getId())).isEmpty();
        assertThat(questionAttachmentRepository.findById(attachment.getId())).isEmpty();
    }

    private Section persistSection() {
        Section section = new Section(
                null,
                SectionType.TALLER,
                "Taller 1",
                "taller-1",
                "Morfometria de cuencas",
                1,
                true,
                NOW);
        entityManager.persist(section);
        entityManager.flush();

        return section;
    }

    @Configuration(proxyBeanMethods = false)
    @EnableTransactionManagement
    @EnableJpaRepositories(basePackageClasses = {
            StudentQuestionRepository.class,
            QuestionAttachmentRepository.class
    })
    static class JpaTestConfig {

        @Bean
        DataSource dataSource() throws SQLException {
            JdbcDataSource dataSource = new JdbcDataSource();
            dataSource.setURL("jdbc:h2:mem:student_question_attachment_persistence;"
                    + "MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1");
            dataSource.setUser("sa");
            dataSource.setPassword("");
            initializeSchema(dataSource);

            return dataSource;
        }

        private static void initializeSchema(DataSource dataSource) throws SQLException {
            String schema = """
                    CREATE TABLE sections (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        type VARCHAR(20) NOT NULL,
                        name VARCHAR(120) NOT NULL,
                        slug VARCHAR(140) NOT NULL,
                        description VARCHAR,
                        display_order INTEGER NOT NULL,
                        active BOOLEAN NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL
                    );

                    CREATE TABLE student_questions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        section_id BIGINT NOT NULL REFERENCES sections(id),
                        nickname VARCHAR(80),
                        question VARCHAR NOT NULL,
                        status VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                    );

                    CREATE TABLE question_attachments (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        question_id BIGINT NOT NULL UNIQUE,
                        public_id VARCHAR(255) NOT NULL UNIQUE,
                        secure_url VARCHAR NOT NULL,
                        format VARCHAR(20) NOT NULL,
                        width INTEGER NOT NULL,
                        height INTEGER NOT NULL,
                        bytes BIGINT NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        CONSTRAINT fk_question_attachments_question
                            FOREIGN KEY (question_id) REFERENCES student_questions(id) ON DELETE CASCADE
                    );
                    """;

            try (Connection connection = dataSource.getConnection();
                    Statement statement = connection.createStatement()) {
                for (String sql : schema.split(";")) {
                    if (!sql.isBlank()) {
                        statement.execute(sql);
                    }
                }
            }
        }

        @Bean
        LocalContainerEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {
            LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
            factory.setDataSource(dataSource);
            factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
            factory.setPackagesToScan("edu.udea.hidrologia");
            factory.setJpaPropertyMap(Map.of(
                    "hibernate.hbm2ddl.auto", "none",
                    "hibernate.show_sql", "false"));

            return factory;
        }

        @Bean
        PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
            return new JpaTransactionManager(entityManagerFactory);
        }
    }
}
